version: '3'  # Docker Composeのバージョン
services:
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    command: python website/manage.py runserver 0.0.0.0:8000

