version: '3'  # Docker Composeのバージョン

services:
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - .:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings_development
    command: python manage.py runserver