# Generated by Django 2.2 on 2020-03-19 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room_reservation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('user', models.CharField(max_length=30)),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('del_flg', models.IntegerField()),
            ],
        ),
    ]
